import type {
  AiTemplateAnalysisResult,
  SimilarTemplateMatch,
} from './analysisTypes';

export const initialAnalysisResults = [
  {
    id: 'ATA-001248',
    templateId: 'TPL-2048',
    name: 'Payment due reminder',
    channel: 'SMS',
    analyzedAt: '2026-06-18 10:32',
    maskedMessage:
      'Your payment of £***.** for account ending **1234 is due on **/**/2026. Please pay by the due date.',
    extractedPattern:
      'Your payment of {amount} for account ending {account_last4} is due on {due_date}. Please pay by the due date.',
    placeholders: ['{amount}', '{account_last4}', '{due_date}'],
    aiMessageType: 'Transaction',
    governanceClassification: 'Servicing',
    confidence: 96,
    qualityScore: 92,
    nearestMatch: {
      templateId: 'TPL-1023',
      name: 'Payment reminder — standard',
      similarity: 95,
    } as SimilarTemplateMatch,
    anomalies: [],
    owner: 'A. Morgan',
    reviewStatus: 'needs-review',
    lifecycleStatus: 'active',
    explanation: [
      'Detected payment context with amount and due date.',
      'Mapped the message to the servicing governance class.',
      'Matched TPL-1023 using normalized template similarity.',
    ],
  },
  {
    id: 'ATA-001249',
    templateId: 'TPL-3091',
    name: 'Card fraud alert',
    channel: 'Push',
    analyzedAt: '2026-06-18 09:08',
    maskedMessage:
      'We flagged a suspicious charge of £***.** on card ending **9876. If this wasn\'t you, call us immediately.',
    extractedPattern:
      'We flagged a suspicious charge of {amount} on card ending {card_last4}. If this wasn\'t you, call us immediately.',
    placeholders: ['{amount}', '{card_last4}'],
    aiMessageType: 'Alert',
    governanceClassification: 'Servicing',
    confidence: 93,
    qualityScore: 88,
    nearestMatch: {
      templateId: 'TPL-3070',
      name: 'Fraud alert — card',
      similarity: 89,
    },
    anomalies: ['contains-possible-PII', 'high-urgency'],
    owner: 'J. Singh',
    reviewStatus: 'reviewed',
    lifecycleStatus: 'active',
    explanation: [
      'Identified as fraud alert due to “suspicious charge” phrase.',
      'High urgency and PII present (card last4).',
    ],
  },
  {
    id: 'ATA-001250',
    templateId: 'TPL-4100',
    name: 'OTP verification',
    channel: 'SMS',
    analyzedAt: '2026-06-17 22:15',
    maskedMessage: 'Your verification code is ****. Do not share this code with anyone.',
    extractedPattern: 'Your verification code is {otp}. Do not share this code with anyone.',
    placeholders: ['{otp}'],
    aiMessageType: 'OTP',
    governanceClassification: 'Regulatory',
    confidence: 99,
    qualityScore: 98,
    nearestMatch: undefined,
    anomalies: [],
    owner: 'L. Chen',
    reviewStatus: 'merged',
    lifecycleStatus: 'active',
    explanation: [
      'Strong OTP signature (short numeric token).',
      'Classified as Regulatory due to authentication context.',
    ],
  },
  {
    id: 'ATA-001251',
    templateId: 'TPL-5120',
    name: 'Mortgage renewal notice',
    channel: 'Email',
    analyzedAt: '2026-06-16 14:02',
    maskedMessage:
      'Your mortgage product is due for renewal on **/**/2026. Contact your advisor or visit our website to discuss options.',
    extractedPattern:
      'Your mortgage product is due for renewal on {renewal_date}. Contact your advisor or visit our website to discuss options.',
    placeholders: ['{renewal_date}'],
    aiMessageType: 'Profile update',
    governanceClassification: 'Servicing',
    confidence: 87,
    qualityScore: 80,
    nearestMatch: {
      templateId: 'TPL-5001',
      name: 'Mortgage renewal — advisor prompt',
      similarity: 83,
    },
    anomalies: ['low-confidence-extraction'],
    owner: 'K. Patel',
    reviewStatus: 'needs-review',
    lifecycleStatus: 'active',
    explanation: [
      'Detected renewal context; date extraction uncertain due to varied formats.',
      'Recommended human review for date parsing.',
    ],
  },
  {
    id: 'ATA-001252',
    templateId: 'TPL-6133',
    name: 'Statement available',
    channel: 'In-app',
    analyzedAt: '2026-06-15 08:45',
    maskedMessage:
      'Your statement for account **1234 is now available to view in the app.',
    extractedPattern: 'Your statement for account {account_last4} is now available to view in the app.',
    placeholders: ['{account_last4}'],
    aiMessageType: 'Marketing',
    governanceClassification: 'Marketing',
    confidence: 82,
    qualityScore: 78,
    nearestMatch: {
      templateId: 'TPL-6100',
      name: 'Statement ready — in-app',
      similarity: 80,
    },
    anomalies: [],
    owner: 'S. Alvarez',
    reviewStatus: 'reviewed',
    lifecycleStatus: 'active',
    explanation: [
      'Generic statement notification; classified as Marketing for opt-in campaigns.',
    ],
  },
  {
    id: 'ATA-001253',
    templateId: 'TPL-7204',
    name: 'Loan disbursement',
    channel: 'Email',
    analyzedAt: '2026-06-14 11:20',
    maskedMessage:
      'We have disbursed your loan of £***.** to account ending **4321. Expected settlement: **/**/2026.',
    extractedPattern:
      'We have disbursed your loan of {amount} to account ending {account_last4}. Expected settlement: {settlement_date}.',
    placeholders: ['{amount}', '{account_last4}', '{settlement_date}'],
    aiMessageType: 'Transaction',
    governanceClassification: 'Servicing',
    confidence: 90,
    qualityScore: 85,
    nearestMatch: {
      templateId: 'TPL-7001',
      name: 'Loan disbursement — confirmation',
      similarity: 88,
    },
    anomalies: ['contains-PII'],
    owner: 'R. Thompson',
    reviewStatus: 'reviewed',
    lifecycleStatus: 'demised',
    explanation: [
      'Disbursement confirmed; contains account last4 and settlement date.',
    ],
  },
] as const satisfies ReadonlyArray<AiTemplateAnalysisResult>;
